### PR TITLE
Resolved assemblies version problem

### LINKED ISSUE #3: SlowCheetah for UWP config file does not work
ITNOA

When using [SlowCheetah](https://github.com/microsoft/slow-cheetah) the config generated path is `application.exe.config` and `App.config` does not use, so PCLAppConfig does not work.

### LINKED ISSUE #30: SlowCheetah for UWP config file does not work
ITNOA

When using [SlowCheetah](https://github.com/microsoft/slow-cheetah) the config generated path is `application.exe.config` and `App.config` does not use, so PCLAppConfig does not work.

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

- I resolved assemblies version problem, and implement shared assemblies. (that popular approach for multi project solution.)

- I added GitHub workflow for CI compile

- I resolved #30 and resolved https://github.com/soroshsabz/PCLAppConfig/issues/3

**Please use nuspec in root directory for creating package to avoid package problem.**

### CODE REVIEW

**Comment by soroshsabz** [comment]
@mrbrl Please review it

**Comment by soroshsabz** [comment]
@mrbrl Any update?

**Comment by soroshsabz** [comment]
@mrbrl @monovo any update?

**Comment by mrbrl** [comment]
Hey @soroshsabz - hope you are doing well. I reviewed your branch, thanks for this! adding a few updates as well and shall push to master this week.

**Comment by soroshsabz** [comment]
@mrbrl Hi, thanks for reply, any update for merging this PR?

thanks

**Comment by soroshsabz** [comment]
@mrbrl  @monovo Any update?

**Comment by soroshsabz** [comment]
@mrbrl  @monovo Any update?

**Comment by soroshsabz** [comment]
@mrbrl @monovo Any update?

**Comment by soroshsabz** [comment]
@mrbrl @monovo Any update?

**Comment by soroshsabz** [comment]
@monovo @mrbrl Any update?

thanks

**Comment by soroshsabz** [comment]
@mrbrl  @monovo  Any update?

thanks

**Comment by soroshsabz** [comment]
Hi agian,

Any update?

**Comment by soroshsabz** [comment]
Hi agian,

Any update?

**Comment by soroshsabz** [comment]
> Hey @soroshsabz - hope you are doing well. I reviewed your branch, thanks for this! adding a few updates as well and shall push to master this week.

@mrbrl If you are using https://github.com/mrbrl/PCLAppConfig/tree/version/1.0.2 instead of merging this PR, you miss all changing in this thread and history of commits and owner of commits. so I suggest you say me any changes that you need or create a PR on https://github.com/soroshsabz/PCLAppConfig as you wish and make all changes that you need and update this PR.

I think copy of changes manually to another branches is incorrect and loss all meta information. so please use normal flow of contributions.

best regards

**Comment by soroshsabz** [comment]
@mrbrl @monovo Did you see https://github.com/mrbrl/PCLAppConfig/pull/23#issuecomment-1151656830 ?

**Comment by soroshsabz** [comment]
@mrbrl @monovo any update?

**Review by mrbrl — APPROVED** [review]

**Comment by mrbrl** [comment]
@soroshsabz merged!

**Comment by soroshsabz** [comment]
thanks :) welcome back ;)

**Pull request merged**
