### PR TITLE
Simplest version for PCLAppConfig

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

Hi,

PCLAppConfig is good project but I think it can be very simpler than now.
I think we can use [Embedded resource file ](http://developer.xamarin.com/guides/xamarin-forms/working-with/files/)instead of use platform specific file.

I injected Stream into configuration manager. so I can remove all extra interface such as ApplicationDomain. As well as I try to decoupled configuration manager from reading config file logic I realized that we have not need IConfigManager any more, so I delete it. and I was able to reduce its dependencies.

I little try to change configuration manager similar to .Net framework configuration manager standard API. 

In addition to I create nuget package for PCLAppConfig projects.

thanks

### CODE REVIEW

**Comment by mrbrl** [comment]
Hi,

Thanks for this. 
Re: Embedded resource vs shared app.config in pcl project, there is an important use case that made me do the extra step of using the file system, deployment server scenario. When we have a build server that produces release ipa and apk and uploads those packages to a deployment server such as octopus (https://octopus.com), we want to the be able to deploy a unique release package to any environment; this involves replacing app.config values in the package, potentially encrypting the app.config as well (as we have control over the reader), resigning the packages and sending the to hockeyapp or google/app store.

We could provide a switch to pick embedded for simple usage, and filesystem for advanced cases.

**Comment by soroshsabz** [comment]
Hi again,

I agree with you, we could provide helper to provide Stream with right way that user want. but I think this business is not in ConfigurationManager and PCLAppConfig, we can keep the PCLAppConfig package as well as simple and non-dependence and elsewhere we can providing such different provider of Stream for different scenario. for example we could create EmbededResourceConfigReader and FileSystemConfigReader class in another package such as PCLAppConfig.Reader pckage.

thanks for your replay.

**Comment by soroshsabz** [comment]
ITNOA

Hi again,

The latest commit now support file system config file as you can see. I hope to there is no issue about merge this request. but if any issue exists please tell me to resolved it if god willing.

In this way the user does not need to do anything other than install the corresponding packages.

Also i will update usage documents and create new package for this library if god willing.

thanks

**Comment by mrbrl** [comment]
Good morning ,

Awesome, will Find a few mins to review and merge this weekend!

Have a great weekend.

**Pull request merged**
